name: Wrapped LiteDoge Contract Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.10 ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm install
      - name: Install truffle
        run: npm install -g truffle
      - name: Setup Binance Scam Chain
        run: |
          bash <(wget -qO- https://raw.githubusercontent.com/binance-chain/node-binary/master/install.sh)
          bnbchaind version
          bnbcli version
          cd $HOME
          bnbchaind init --moniker test
          bnbchaind testnet --v 1 --chain-id local-testnet
          cp ./mynetwork/config/genesis $home/config
          echo "\n" >> $home/config/app.toml
          echo 'FixSignBytesOverflowHeight = 1' >> $home/config/app.toml
          bnbchaind start --home $home
      - name: Run JavaScript Tests
        run: npm run tests
